### Variables
# @baseUrl =   https://myapp.amroaltayeb14.workers.dev 
# For local testing, uncomment the line below:
@studentToken = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6Miwicm9sZSI6InN0dWRlbnQiLCJ1c2VyTmFtZSI6ImFsaSIsImlhdCI6MTc2NTgzMTA0NywiZXhwIjoxNzY2NDM1ODQ3fQ.p9MQ_nYqEyQo0dLgXkP6esqdS4HbD4Dnp2_Uq1-TRUQ
@baseUrl = http://localhost:8787
@adminToken = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwidXNlck5hbWUiOiJhbXJvIiwiaWF0IjoxNzY1ODMxMjgyLCJleHAiOjE3NjY0MzYwODJ9.qm3rPB_5fmskB_I6M2P_3Kw2mazinH0SvKb_7q9PuBg

### get all users (to check what users exist)
GET {{baseUrl}}/users

### signup
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "userName": "ali",
  "email": "ali@gmail.com",
  "password": "123456",
  "role": "student"
}
### login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "amro@gmail.com",
  "password": "123456"
}
### get student
GET {{baseUrl}}/users/students
### get admins with their schools
GET {{baseUrl}}/users/admin
### get teachers
GET {{baseUrl}}/users/teachers
### delete user
DELETE {{baseUrl}}/users/12
Authorization: Bearer {{adminToken}}


###################SCHOOL###################
### create school
POST {{baseUrl}}/schools
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "altwafeq",
  "adminId": 1
}
### get schools
GET {{baseUrl}}/schools

### delete school
DELETE {{baseUrl}}/schools/2
Authorization: Bearer {{adminToken}}