### Variables
# @baseUrl =   https://myapp.amroaltayeb14.workers.dev 
# For local testing, uncomment the line below:
@studentToken = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6Miwicm9sZSI6InN0dWRlbnQiLCJ1c2VyTmFtZSI6ImFsaSIsImlhdCI6MTc2NTg0MTIyMSwiZXhwIjoxNzY2NDQ2MDIxfQ.rUf-L_DRA_H1g5cxzbUN7Irw5zdOtJmYO9_fo7uTXhQ
@baseUrl = http://localhost:8787
@adminToken = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwidXNlck5hbWUiOiJhbXJvIiwiaWF0IjoxNzY1ODQxODY2LCJleHAiOjE3NjY0NDY2NjZ9.EQa9mKVL8G1HIOj5gLTH_oYFaO4ablpT2n1VeXaYLgs

### get all users (to check what users exist)
GET {{baseUrl}}/users

### signup
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "userName": "mohamed",
  "email": "mohamed@gmail.com",
  "password": "123456",
  "role": "teacher"
}
### login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "amro@gmail.com",
  "password": "123456"
}
### get student
GET {{baseUrl}}/users/students
### get admins with their schools
GET {{baseUrl}}/users/admin
### get teachers
GET {{baseUrl}}/users/teachers
### delete user
DELETE {{baseUrl}}/users/12
Authorization: Bearer {{adminToken}}


###################SCHOOL###################
### create school
POST {{baseUrl}}/schools
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "almanhal",
  "adminId": 1
}
### get schools
GET {{baseUrl}}/schools

### delete school
DELETE {{baseUrl}}/schools/2
Authorization: Bearer {{adminToken}}

###################CLASSES###################
### create class
POST {{baseUrl}}/classes
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "class2",
  "schoolId": 1
}
### get classes
GET {{baseUrl}}/classes
Authorization: Bearer {{adminToken}}
### delete class
DELETE {{baseUrl}}/classes/3
Authorization: Bearer {{adminToken}}


###################SUBJECT###################
### create subject
POST {{baseUrl}}/subjects
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "science"
}
### get subjects
GET {{baseUrl}}/subjects
Authorization: Bearer {{adminToken}}
### delete subject
DELETE {{baseUrl}}/subjects/2
Authorization: Bearer {{adminToken}}

###################CONNECTION###################
### connect between class and subject
POST {{baseUrl}}/connections/connect
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "classRoomId": 1,
  "subjectId": 1,
  "teacherId": 3
}
### disconnect between class and subject
DELETE {{baseUrl}}/connections/disconnect
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "classRoomId": 1,
  "subjectId": 1,
  "teacherId": 1
}
### get all connections data with school name
GET {{baseUrl}}/connections/all
Authorization: Bearer {{adminToken}}

###################ENROLLMENTS###################
### enroll student in class
POST {{baseUrl}}/enrollments/enroll
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "studentId":2,
  "classRoomId": 1
}
### get all enrollments
GET {{baseUrl}}/enrollments/all
Authorization: Bearer {{adminToken}}

