### Variables
# @baseUrl =   https://myapp.amroaltayeb14.workers.dev 
# For local testing, uncomment the line below:
@studentToken = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6Miwicm9sZSI6InN0dWRlbnQiLCJ1c2VyTmFtZSI6ImFsaSIsImlhdCI6MTc2NTgzMTA0NywiZXhwIjoxNzY2NDM1ODQ3fQ.p9MQ_nYqEyQo0dLgXkP6esqdS4HbD4Dnp2_Uq1-TRUQ
@baseUrl = http://localhost:8787
@adminToken = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwidXNlck5hbWUiOiJhbXJvQWRtaW4iLCJpYXQiOjE3NjU4MzgxNjUsImV4cCI6MTc2NjQ0Mjk2NX0.50qrABYju2cCcH0Wyy0BgrIYb30j-EC0o60kyqHdPww

### get all users (to check what users exist)
GET {{baseUrl}}/users

### signup
POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "userName": "amroAdmin",
  "email": "amroAdmin@gmail.com",
  "password": "123456",
  "role": "admin"
}
### login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "amroAdmin@gmail.com",
  "password": "123456"
}
### get student
GET {{baseUrl}}/users/students
### get admins with their schools
GET {{baseUrl}}/users/admin
### get teachers
GET {{baseUrl}}/users/teachers
### delete user
DELETE {{baseUrl}}/users/12
Authorization: Bearer {{adminToken}}


###################SCHOOL###################
### create school
POST {{baseUrl}}/schools
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "altwafeq",
  "adminId": 1
}
### get schools
GET {{baseUrl}}/schools

### delete school
DELETE {{baseUrl}}/schools/2
Authorization: Bearer {{adminToken}}

###################CLASSES###################
### create class
POST {{baseUrl}}/classes
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "class2",
  "schoolId": 1
}
### get classes
GET {{baseUrl}}/classes
Authorization: Bearer {{adminToken}}
### delete class
DELETE {{baseUrl}}/classes/3
Authorization: Bearer {{adminToken}}


